### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by Anunciosservidor** [Daniellop1/task-cli#1]
Hi, I have tried to install the cli from command npm install @ daniellop1 / dglobal-tasks @ 1.2.3 but it doesn't work

**Comment by Daniellop1** [comment]
Hi, we are aware of the bug and are in the process of fixing it. You can continue installing the cli from npm i dglobal-tasks

**Comment by Anunciosservidor** [comment]
> Hi, we are aware of the bug and are in the process of fixing it. You can continue installing the cli from npm i dglobal-tasks

When do you think they are going to fix it?

**Comment by Daniellop1** [comment]
> > Hi, we are aware of the bug and are in the process of fixing it. You can continue installing the cli from npm i dglobal-tasks
> 
> When do you think they are going to fix it?

We are on it, please be patient

**Comment by Daniellop1** [comment]
The problem has been fixed and can now be installed. https://github.com/Daniellop1/task-cli/packages/536784
